---
title: "Summary [(Full CV)](https://github.com/Joemillard/joemillard.github.io/blob/main/docs/Joe-Millard_CV.pdf)"
---

***

### **Education**
- **PhD Computational Ecology – UCL London NERC DTP** (2017-2021)
  - Thesis: Causes and consequences of pollinator biodiversity change in the the Anthropocene
- **MSc Biodiversity and Conservation, Distinction (1st) – The University of Leeds** (2014-2015)
  - Thesis: A Satellite Telemetry Investigation of Caspian Seal (*Pusa caspica*) Activity Budgets
- **BSc Zoology, Upper second-class honours (2:1) – The University of Leeds** (2011-2014) 
  - Thesis: Of Molecules and Morphology: An Extended Review of the Eutherian Radiation 

***

### **Employment**
- **Leverhulme Early Career Fellow – the University of Cambridge** (2024-present)
- **Postdoctoral researcher – the Natural History Museum in London** (2022-2024)
- **Postdoctoral researcher – Leverhulme Centre for Demographic Science, the University of Oxford** (2021-2022)
- **UCL Postgraduate teaching assistant** (2019-2021)
- **Programme Assistant – UNEP-WCMC** (September 2016-June 2017) 
- **Publishing Assistant – Nature Publishing Group** (November 2015-September 2016) 
- **Research Assistant – Action for the Wild** (Summer 2014) & **Cetacean Research and Rescue Unit** (June 2016)

***

### **Publications**

##### **Peer reviewed**
1.	Skinner, G., Cooke, R., Roy, H. E., Isaac, N. J. B., Outhwaite, C. L., Rodger, J., & **Millard, J.**, Global meta-analysis reveals overall negative impacts of invasive species on terrestrial insects, despite highly variable responses. Nature Communications (accepted) 
2.	Barnes, L., Wenban-Smith, Skinner, G., E., Dicks, L., **Millard, J.**, & Bladon, A., (2025). Differing impacts of livestock farming and ranching on aquatic insect biodiversity: A global meta-analysis. Global Change Biology. 31(9), p.e70513. DOI: https://doi.org/10.1111/gcb.70513.
3.	**Millard, J.**, Skinner, G., Bladon, A. J., Cooke, R., Outhwaite, C. L., Rodger, J. G., Barnes, L. A., Isip, J., Keum, J., Raw, C., Wenban-Smith, E., Dicks, L. V., Hui, C., Jones, J. I., Woodcock, B., Isaac, N. J., & Purvis, A. (2025). A multi-threat meta-analytic database for understanding insect biodiversity change. Diversity and Distributions. 31(5), p.e70025. DOI: https://doi.org/10.1111/ddi.70025. 
4.	Cooke, R., Outhwaite, C. L., Bladon, A. J., **Millard, J.**, Rodger, J. G., Dong, Z., Dyer, E. E., Edney, S., Murphy, J. F., Dicks, L. V., Hui, C., Jones, J. I., Newbold, T., Purvis, A., Roy, H. E., Woodcock, B. A. & Isaac, N. J. B. (2025). Integrating multiple evidence streams to understand insect biodiversity change. Science. 388, no. 6742. DOI: https://doi.org/10.1126/science.adq2110. 
5.	Johnson, T.F., **Millard, J.**, & Evans, L.C., (2025). More work is needed to identify how people perceive and value nature. Nature Reviews Biodiversity. pp.1-2. DOI: https://doi.org/10.1038/s44358-025-00047-8.
6.	Williams, J., Newbold, T., **Millard, J.**, Groner, V., & Pearson, R., (2024). Important pollinators respond less negatively to anthropogenic land use than other animals. Ecology and Evolution. 14(11), p.e70486. DOI: https://doi.org/10.1002/ece3.70486. 
7.	**Millard, J.**, Christie, A., Dicks, L., Isip, J., Johnson, T.F., Skinner, G., & Spake, R., (2024). ChatGPT is likely reducing opportunity for support, friendship, and learned kindness in research. Methods in Ecology and Evolution. 15(10), pp.1764-1766. DOI: https://doi.org/10.1111/2041-210X.14395. 
8.	Johnson, T.F., Simmons, B., Millard, J., Strydom, T., Danet A., & Evans, L., (2024). Pressure to publish introduces LLM risks. Methods in Ecology and Evolution. 15(10), pp.1771-1773. DOI: https://doi.org/10.1111/2041-210X.14397. 
9.	Outhwaite, C.L., Cooke, R., **Millard, J.** & Bladon, A.J., (2024). Pervasive and synergistic effects of climate change. In Routledge Handbook of Insect Conservation (pp. 92-107). Routledge. DOI: https://doi.org/10.4324/9781003285793-9 
10.	Bladon, A.J., Cooke, R., **Millard, J.** & Outhwaite, C.L., (2024). Practical solutions to climate change for insect conservation. In Routledge Handbook of Insect Conservation (pp. 108-118). Routledge. DOI: https://doi.org/10.4324/9781003285793-10 
11.	Scheepens, D., **Millard, J.**, Farrell, M., & Newbold, T., (2024). Large language models help facilitate the automated synthesis of information on potential pest controllers. Methods in Ecology and Evolution. 15(7), pp.1261-1273. DOI: https://doi.org/10.1111/2041-210X.14341. 
12.	Veríssimo, D., Johnson, T.F., **Millard, J.**, & Roll, U., (2023). Adopt digital tools to monitor social dimensions of the global biodiversity framework. Conservation Letters. 17(1). DOI: https://doi.org/10.1111/conl.12991. 
13.	**Millard, J.**, Outhwaite, C.L., Ceaușu, S., Carvalheiro, L.G., da Silva e Silva, F.D., Dicks, L.V., Ollerton, J. & Newbold, T., (2023). Key tropical crops at risk from pollinator loss due to climate change and land use. Science Advances. 9(41), p.eadh0756. DOI: https://doi.org/10.1126/sciadv.adh0756. 
14.	Johnson, T.F., Cornford, R., Dove, S., Freeman, R., & **Millard, J.**, (2023). Achieving a real‐time online monitoring system for conservation culturomics. Conservation Biology. 37(4), p.e14096. DOI: https://doi.org/10.1111/cobi.14096. 
15.	Skinner, G., Cooke, R., Keum, J., Purvis, A., Raw, C., Woodcock, B.A., & **Millard, J.**, (2023). Dynameta: A dynamic platform for ecological meta-analyses in R Shiny. SoftwareX. 23, p.101439. DOI: https://doi.org/10.1016/j.softx.2023.101439. 
16.	Cornford, R., **Millard, J.**, González‐Suárez, M., Freeman, R., & Johnson, T.F., (2022). Automated synthesis of biodiversity knowledge requires better tools and standardised research output. Ecography. 2022(3), p.e06068. DOI: https://doi.org/10.1111/ecog.06068.
17.	**Millard, J.**, Gregory, R.D., Jones, K.E. & Freeman, R., (2021). The species awareness index as a conservation culturomics metric for public biodiversity awareness. Conservation Biology. 35(2), pp.472-482. DOI: https://doi.org/10.1111/cobi.13701. 
18.	**Millard, J.**, Outhwaite, C.L., Kinnersley, R., Freeman, R., Gregory, R.D., Adedoja, O., Gavini, S., Kioko, E., Kuhlmann, M., Ollerton, J. Ren, Z.X., & Newbold T., (2021). Global effects of land-use intensity on local pollinator biodiversity. Nature Communications. 12(1), p.2902. DOI: https://doi.org/10.1038/s41467-021-23228-3. 
19.	**Millard, J.**, Freeman, R. & Newbold, T., (2020). Text‐analysis reveals taxonomic and geographic disparities in animal pollination literature. Ecography. 43(1), pp.44-59. DOI: https://doi.org/10.1111/ecog.04532. 
20.	Newbold, T., Adams, G.L., Albaladejo Robles, G. ,Boakes, E.H., Braga Ferreira, G., Chapman, A.S., Etard, A., Gibb, R., **Millard, J.**, Outhwaite, C.L., Williams, J.J. & Newbold, T., (2019). Climate and land-use change homogenise terrestrial biodiversity, with consequences for ecosystem functioning and human well-being. Emerging Topics in Life Sciences. 3(2), pp.207-219. DOI: https://doi.org/10.1042/ETLS20180135.

##### **In prep**
21. **Millard, J.**, Akimova, E., Ding, X., Leasure, D., Zhao, B., Mills, M., Stringent COVID-19 government restrictions were associated with a marked increase in Twitter activity in Europe. SocArXiv. DOI: https://doi.org/10.31235/osf.io/g9apk
22.	**Millard, J**. Mobilising central bank digital currency to bend the curve of biodiversity loss. EcoEvoRxiv. DOI: https://doi.org/10.32942/X2TC7H
23. Cooke, R., Outhwaite, C., Bladon, A., **Millard, J.**, Rodger, J., Dong, Z., Dyer E., Edney, S., Murphy, J., Dicks, L., Hui, C., Jones, I., Newbold, T., Purvis, A., Roy, H., Woodcock, B., & Isaac, N. J. B. Insect Insect Time Series (IN-TIME), a database of worldwide insect trends
24. Wenban-Smith, E., Barnes, L., **Millard, J.**, Dicks, L., Turner, E,. Bladon, A., Meta-analysis of extreme temperature effects on the abundance and survival of Hymenoptera and Lepidoptera
25. Outhwaite, C., Purvis A., Newbold, T., Bladon, A., Cooke, R., **Millard, J.,** Dicks L., Isaac, N., The response of Hymenopteran (Bees, Wasps & Ants) biodiversity to a changing world
26. **Millard, J.**, Varah, A., Isip, J., Tudge, S., Contu, S., Burton, V., Johnson, T., Purvis, A., De Palma, A., Predictions of biodiversity change are question dependent

***

### **Invited talks and Symposia**
- **Entomology 2025 evidence synthesis symposium**: co-lead, keynote speaker, and panellist at a symposium along with Eliza Grames on insect biodiversity change
- **Royal Society Recovering Nature event**: building on Georgina Mace's work to ensure a biodiverse
and liveable future – invited as one of 12 contributed speakers building on Georgina’s work
- **ICCB 2023 round-table symposium**; Large scale monitoring of perceptions of nature: state of the art
and ways forward – co-author on accepted proposal, and then group lead on presentation entitled
“Achieving a real-time online monitoring system for conservation culturomics”
- **NHM & Turing AI Lunch Series** – invite only lunch for AI scientists working in the natural and
environmental sciences
- **Linnaean Student Conference 2019** – The importance and diversity of animal pollination
(https://www.youtube.com/watch?v=qn0sCxJiTdI&t=5854s)
- **Planet PhD podcast** – Pollinator biodiversity in a changing world
(https://planetphd.podbean.com/e/joe-millard-pollinator-biodiversity-in-a-changing-world/)
- **University College London seminar 2019** – Text-analysis reveals taxonomic and geographic disparities
in animal pollination literature
- **University of São Paulo, Brazil 2019** – Postgraduate study in the UK: How, when and why?
- **Natural History Museum seminar 2022** – Worldwide vulnerability of local pollinator abundance and crop
pollination to land-use and climate change
- **University of Oxford seminar 2021** - Pollinators, culturomics, and chronotype: a summary of my
background and ideas for future research
- **Online University College London seminar 2021** – The Species Awareness Index